import { ClassifiedListing } from '@/types/classifieds';

export const mockClassifieds: ClassifiedListing[] = [
  {
    id: 'c1',
    slug: 'senior-software-engineer-bhel-trichy',
    title: 'Senior Software Engineer – Industrial IoT',
    description:
      'BHEL Trichy is hiring experienced software engineers for its digital transformation team. Work on real-time monitoring systems for power plant equipment. 5+ years of experience required.',
    category: 'jobs',
    subCategory: 'IT / Software',
    priceType: 'on-request',
    currency: 'INR',
    location: { area: 'Woraiyur', city: 'Trichy', pincode: '620003' },
    images: ['https://images.unsplash.com/photo-1497366216548-37526070297c?w=600&q=80'],
    contact: { name: 'BHEL HR Team', whatsappEnabled: false, email: 'careers@bhel-trichy.in' },
    postedAt: '2026-04-03T10:00:00Z',
    isVerified: true,
    isPremium: true,
    viewCount: 1240,
  },
  {
    id: 'c2',
    slug: '2bhk-apartment-thillai-nagar',
    title: '2 BHK Apartment for Rent – Thillai Nagar',
    description:
      'Spacious 2BHK apartment on the 3rd floor, fully furnished. Close to Cauvery Medical Centre. 24/7 security, covered parking. Ideal for small families.',
    category: 'real-estate',
    subCategory: 'Apartment',
    price: 18000,
    priceType: 'fixed',
    currency: 'INR',
    location: { area: 'Thillai Nagar', city: 'Trichy', pincode: '620018' },
    images: ['https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=600&q=80'],
    contact: { name: 'Rajesh Kumar', phone: '94XXXXXX12', whatsappEnabled: true },
    postedAt: '2026-04-04T07:30:00Z',
    isVerified: true,
    isPremium: false,
    viewCount: 430,
  },
  {
    id: 'c3',
    slug: 'honda-city-2022-for-sale',
    title: '2022 Honda City V CVT – Single Owner, Top Condition',
    description:
      'Honda City 1.5L V CVT, Petrol, 2022 model. 28,000 km driven. All service records available. Sunroof, Honda Sensing ADAS. Ruby Red color. Selling due to relocation.',
    category: 'vehicles',
    subCategory: 'Cars',
    price: 1150000,
    priceType: 'negotiable',
    currency: 'INR',
    location: { area: 'KK Nagar', city: 'Trichy', pincode: '620021' },
    images: [
      'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=600&q=80',
      'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=600&q=80',
    ],
    condition: 'like-new',
    contact: { name: 'Vijay Anand', phone: '98XXXXXX34', whatsappEnabled: true },
    postedAt: '2026-04-02T16:00:00Z',
    isVerified: true,
    isPremium: true,
    viewCount: 890,
  },
  {
    id: 'c4',
    slug: 'iphone-14-pro-256gb',
    title: 'iPhone 14 Pro 256GB – Deep Purple, Like New',
    description:
      'iPhone 14 Pro, 256GB, Deep Purple. Purchased 8 months ago, no scratches. Original box and accessories included. Battery health 95%. Genuine reason for sale – switching to Android.',
    category: 'electronics',
    subCategory: 'Mobile Phones',
    price: 82000,
    priceType: 'fixed',
    currency: 'INR',
    location: { area: 'Cantonment', city: 'Trichy', pincode: '620001' },
    images: ['https://images.unsplash.com/photo-1678685888221-cda773a3dcdb?w=600&q=80'],
    condition: 'like-new',
    contact: { name: 'Aarthi S', whatsappEnabled: true },
    postedAt: '2026-04-04T09:00:00Z',
    isVerified: false,
    isPremium: false,
    viewCount: 210,
  },
  {
    id: 'c5',
    slug: 'tamil-bride-seeking-groom-srirangam',
    title: 'Alliance Sought – 27 yr, Software Engineer, Srirangam',
    description:
      'Tamil Brahmin girl, 27 years, height 5\'4", working as Software Engineer in Chennai (TCS). Looking for a well-settled groom aged 28-33. Pillai star, Rohini nakshathram. Parents can be contacted.',
    category: 'matrimony',
    subCategory: 'Bride',
    priceType: 'free',
    currency: 'INR',
    location: { area: 'Srirangam', city: 'Trichy', pincode: '620006' },
    images: [],
    contact: { name: 'Parents of Bride', phone: '90XXXXXX56', whatsappEnabled: false },
    postedAt: '2026-04-01T11:00:00Z',
    isVerified: true,
    isPremium: false,
    viewCount: 1780,
  },
  {
    id: 'c6',
    slug: 'maths-physics-home-tutor-ariyamangalam',
    title: 'Home Tutor for Maths & Physics (11th & 12th Std)',
    description:
      'Experienced private tutor with 10+ years, specializing in Maths and Physics for Class 11 and 12 (State Board & CBSE). Regular batches and crash courses available. 95% pass rate.',
    category: 'education',
    subCategory: 'Coaching',
    price: 2500,
    priceType: 'fixed',
    currency: 'INR',
    location: { area: 'Ariyamangalam', city: 'Trichy', pincode: '620010' },
    images: ['https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=600&q=80'],
    contact: { name: 'Senthil Kumar', phone: '99XXXXXX78', whatsappEnabled: true },
    postedAt: '2026-03-30T08:00:00Z',
    isVerified: true,
    isPremium: false,
    viewCount: 560,
  },
  {
    id: 'c7',
    slug: 'commercial-shop-puthur-for-sale',
    title: 'Commercial Shop for Sale – 600 sqft, Puthur Main Road',
    description:
      'Prime commercial space on Puthur main road, ground floor, 600 sqft. Currently rented out at ₹25,000/month. Good return on investment. DTCP approved, clear documents.',
    category: 'real-estate',
    subCategory: 'Commercial',
    price: 4500000,
    priceType: 'negotiable',
    currency: 'INR',
    location: { area: 'Puthur', city: 'Trichy', pincode: '620017' },
    images: ['https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=600&q=80'],
    contact: { name: 'Lakshmi Properties', phone: '93XXXXXX90', whatsappEnabled: true },
    postedAt: '2026-03-28T12:00:00Z',
    isVerified: true,
    isPremium: true,
    viewCount: 670,
  },
  {
    id: 'c8',
    slug: 'ac-repair-service-trichy',
    title: 'AC Repair & Service – All Brands, Same Day Service',
    description:
      'Professional AC repair and annual maintenance service for all brands (Voltas, Daikin, LG, Samsung). Split AC cleaning ₹499. Gas filling and PCB repair available. Free pickup & delivery for window ACs.',
    category: 'services',
    subCategory: 'Home Services',
    price: 499,
    priceType: 'fixed',
    currency: 'INR',
    location: { area: 'Tennur', city: 'Trichy', pincode: '620017' },
    images: ['https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=600&q=80'],
    contact: { name: 'Cool Air Services', phone: '88XXXXXX12', whatsappEnabled: true },
    postedAt: '2026-04-03T14:00:00Z',
    isVerified: true,
    isPremium: false,
    viewCount: 340,
  },
];
